name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    container: python:${{ matrix.python }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.13', python: '3.13', tox: py313}
          - {name: '3.12', python: '3.12', tox: py312}
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: 'format', python: '3.13', tox: format}
          - {name: 'mypy', python: '3.13', tox: mypy}
          - {name: 'pep8', python: '3.13', tox: pep8}
          - {name: 'package', python: '3.13', tox: package}

    steps:
      - uses: pgjones/actions/tox@dbbee601c084d000c4fc711d4b27cb306e15ead1 # v1
        with:
          environment: ${{ matrix.tox }}

  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest

    steps:
      - uses: pgjones/actions/zizmor@dbbee601c084d000c4fc711d4b27cb306e15ead1 # v1

  compliance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.13'

      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip

      - run: pip install openapi-spec-validator pydantic .

      - run: cd compliance && QUART_APP=todo:app quart schema | openapi-spec-validator -
